### ISSUE TITLE
Still supported ?

### ISSUE THREAD

**Issue by bog500** [1am3r/PlayerMarkers#5]
Is this project still supported ?  There hasn't been a commit in the last 3 years and the 2 pull requests (1 is almost 1 year old) were never answered.

I use this plugin on my server and made a few changes in my fork : include the 2 changes from the pull requests, added commands, permissions and update checker.

If you don't plan on supporting this project anymore could you give write access to the plugin on bukkitdev so I could publish the updated version ?

**Comment by 1am3r** [comment]
Sadly I don't have enough time anymore to do much for or with Minecraft Moding.
Send me am PM in bukkitdev, I'll add you to the project.
